doi_suffix,error
"2015', '804794","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 804794.pdf\'\n'"
"jbcr', 'iry051","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/jbcr, iry051.pdf\'\n'"
"2012', '241754","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 241754.pdf\'\n'"
"2013', '680326","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 680326.pdf\'\n'"
"1361-6579', 'abbb6e","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/1361-6579, abbb6e.pdf\'\n'"
"ajh', 'hpx145","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajh, hpx145.pdf\'\n'"
0006-3568(2006)56[325:tplinu]2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0006-3568(2006)56[325:tplinu]2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0006-3568(2006)56[325:tplinu]2.0.co;2.pdf'\n"""
s0008-6363(95)00199-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(95)00199-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(95)00199-9.pdf'\n"""
"eurpub', 'cki159","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurpub, cki159.pdf\'\n'"
"occmed', 'kqx127","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqx127.pdf\'\n'"
"ajcn', '72.2.512s","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 72.2.512s.pdf\'\n'"
"conphys', 'cow008","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cow008.pdf\'\n'"
"ndt', '13.8.2023","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, 13.8.2023.pdf\'\n'"
s0006-3495(99)77417-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0006-3495(99)77417-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0006-3495(99)77417-5.pdf'\n"""
"conphys', 'cov060","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cov060.pdf\'\n'"
"2016', '6050193","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 6050193.pdf\'\n'"
"ehjci', 'jew128","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jew128.pdf\'\n'"
"sleep', '31.1.104","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/sleep, 31.1.104.pdf\'\n'"
"gerona', 'glx180","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glx180.pdf\'\n'"
"eurheartj', 'ehq058","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, ehq058.pdf\'\n'"
"acem', '35094","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/acem, 35094.pdf\'\n'"
"2014', '184693","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 184693.pdf\'\n'"
"occmed', 'kqh008","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqh008.pdf\'\n'"
"2022', '5966488","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 5966488.pdf\'\n'"
ijpsr.0975-8232.11(11).5775-82,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/ijpsr.0975-8232.11(11).5775-82.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/ijpsr.0975-8232.11(11).5775-82.pdf'\n"""
0022-3999(84)90079-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0022-3999(84)90079-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0022-3999(84)90079-5.pdf'\n"""
s0895-7061(01)02223-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0895-7061(01)02223-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0895-7061(01)02223-3.pdf'\n"""
"bja', 'aeu560","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aeu560.pdf\'\n'"
"ehjci', 'jeu312","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jeu312.pdf\'\n'"
"icb', 'icx012","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, icx012.pdf\'\n'"
"humrep', 'dep411","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/humrep, dep411.pdf\'\n'"
s0008-6363(00)00143-7,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(00)00143-7.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(00)00143-7.pdf'\n"""
"milmed', '165.5.418","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, 165.5.418.pdf\'\n'"
"2016', '8262383","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 8262383.pdf\'\n'"
"2017', '8083738","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 8083738.pdf\'\n'"
"bja', 'aeu404","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aeu404.pdf\'\n'"
"2012', '750286","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 750286.pdf\'\n'"
"milmed', '166.3.253","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, 166.3.253.pdf\'\n'"
"ptj', 'pzz038","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, pzz038.pdf\'\n'"
"2016', '1535367","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 1535367.pdf\'\n'"
"heapro', 'daw106","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/heapro, daw106.pdf\'\n'"
"einstein_journal', '2020ao5256","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/einstein_journal, 2020ao5256.pdf\'\n'"
"ejechocard', 'jer246","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejechocard, jer246.pdf\'\n'"
"eurheartj', 'ehv337","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, ehv337.pdf\'\n'"
"2012', '589164","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 589164.pdf\'\n'"
0002-9149(85)91072-0,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0002-9149(85)91072-0.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0002-9149(85)91072-0.pdf'\n"""
"annhyg', 'mem004","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/annhyg, mem004.pdf\'\n'"
"2016', '6739150","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 6739150.pdf\'\n'"
"ndt', 'gfy045","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, gfy045.pdf\'\n'"
"2014', '151282","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 151282.pdf\'\n'"
"milmed', '167.8.692","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, 167.8.692.pdf\'\n'"
"gerona', 'glu065","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glu065.pdf\'\n'"
"gerona', '57.4.m203","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 57.4.m203.pdf\'\n'"
"icb', '45.3.405","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, 45.3.405.pdf\'\n'"
jds.s0022-0302(05)72712-0,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/jds.s0022-0302(05)72712-0.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/jds.s0022-0302(05)72712-0.pdf'\n"""
s0378-1097(01)00416-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0378-1097(01)00416-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0378-1097(01)00416-5.pdf'\n"""
"conphys', 'cow019","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cow019.pdf\'\n'"
"ageing', 'afl127","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, afl127.pdf\'\n'"
"ehjci', 'jev147","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jev147.pdf\'\n'"
s0008-6363(98)00102-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(98)00102-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(98)00102-3.pdf'\n"""
s0895-7061(03)01003-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0895-7061(03)01003-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0895-7061(03)01003-3.pdf'\n"""
"gerona', '55.10.m570","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 55.10.m570.pdf\'\n'"
"2012', '810859","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 810859.pdf\'\n'"
"ajcn', 'nqz188","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, nqz188.pdf\'\n'"
"2014', '230271","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 230271.pdf\'\n'"
0741-5214(88)90379-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0741-5214(88)90379-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0741-5214(88)90379-5.pdf'\n"""
"2017', '7853034","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 7853034.pdf\'\n'"
"ndt', 'gfm368","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, gfm368.pdf\'\n'"
"2015', '538732","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 538732.pdf\'\n'"
"ejechocard', 'jeq105","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejechocard, jeq105.pdf\'\n'"
"conphys', 'coy053","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, coy053.pdf\'\n'"
1533-4287(2004)18<584:teoihi>2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/1533-4287(2004)18<584:teoihi>2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/1533-4287(2004)18<584:teoihi>2.0.co;2.pdf'\n"""
"gerona', '51a.4.b247","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 51a.4.b247.pdf\'\n'"
"ejcts', 'ezw104","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejcts, ezw104.pdf\'\n'"
"occmed', 'kqu138","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqu138.pdf\'\n'"
"ajcn', '75.4.734","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 75.4.734.pdf\'\n'"
"milmed', 'usx155","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, usx155.pdf\'\n'"
"2010', '195729","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2010, 195729.pdf\'\n'"
"rheumatology', 'ket283","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, ket283.pdf\'\n'"
"1361-6579', 'aa66c2","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/1361-6579, aa66c2.pdf\'\n'"
s0008-6363(01)00210-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(01)00210-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(01)00210-3.pdf'\n"""
"2015', '909561","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 909561.pdf\'\n'"
"gerona', '53a.4.b259","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 53a.4.b259.pdf\'\n'"
"2022', '8720661","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 8720661.pdf\'\n'"
"conphys', 'cox038","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cox038.pdf\'\n'"
"ptj', 'pzy147","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, pzy147.pdf\'\n'"
s0895-7061(98)00138-1,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0895-7061(98)00138-1.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0895-7061(98)00138-1.pdf'\n"""
"jn', '135.5.1088","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/jn, 135.5.1088.pdf\'\n'"
"2009', '927385","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2009, 927385.pdf\'\n'"
"ehjci', 'jes067","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jes067.pdf\'\n'"
s0195-668x(02)00822-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0195-668x(02)00822-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0195-668x(02)00822-9.pdf'\n"""
"ptj', '81.11.1790","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 81.11.1790.pdf\'\n'"
"2022', '9023144","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 9023144.pdf\'\n'"
"2013', '516767","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 516767.pdf\'\n'"
"ajcn', 'nqy247","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, nqy247.pdf\'\n'"
"ajh', 'hpw028","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajh, hpw028.pdf\'\n'"
"2021', '2356869","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 2356869.pdf\'\n'"
"rheumatology', '37.2.196","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, 37.2.196.pdf\'\n'"
"2016', '2372741","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 2372741.pdf\'\n'"
"ndt', 'gfr014","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, gfr014.pdf\'\n'"
"2012', '349209","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 349209.pdf\'\n'"
s1010-7940(97)01211-6,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1010-7940(97)01211-6.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1010-7940(97)01211-6.pdf'\n"""
"alcalc', 'agn108","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/alcalc, agn108.pdf\'\n'"
s0008-6363(01)00426-6,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(01)00426-6.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(01)00426-6.pdf'\n"""
"ndt', 'gfh560","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, gfh560.pdf\'\n'"
"ptj', '81.11.1801","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 81.11.1801.pdf\'\n'"
s1388-9842(03)00156-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1388-9842(03)00156-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1388-9842(03)00156-9.pdf'\n"""
"2017', '1342842","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 1342842.pdf\'\n'"
"2021', '8288747","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 8288747.pdf\'\n'"
"2013', '952350","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 952350.pdf\'\n'"
s0026-0495(99)90004-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0026-0495(99)90004-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0026-0495(99)90004-5.pdf'\n"""
s0008-6363(96)00157-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(96)00157-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(96)00157-5.pdf'\n"""
"ajcn', '71.2.450","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 71.2.450.pdf\'\n'"
1548-8659(2001)130<0783:crtvfe>2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/1548-8659(2001)130<0783:crtvfe>2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/1548-8659(2001)130<0783:crtvfe>2.0.co;2.pdf'\n"""
"icb', 'icx075","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, icx075.pdf\'\n'"
"gerona', 'gly159","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, gly159.pdf\'\n'"
"2019', '6239058","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2019, 6239058.pdf\'\n'"
"2021', '6684568","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 6684568.pdf\'\n'"
"ejcts', 'ezz355","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejcts, ezz355.pdf\'\n'"
"0967-3334', '31', '9', '014","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/0967-3334, 31, 9, 014.pdf\'\n'"
"0967-3334', '30', '3', '001","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/0967-3334, 30, 3, 001.pdf\'\n'"
"aje', 'kwq362","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/aje, kwq362.pdf\'\n'"
"conphys', 'cot015","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cot015.pdf\'\n'"
"2014', '602620","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 602620.pdf\'\n'"
"2021', '7424857","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 7424857.pdf\'\n'"
"ajh', 'hpy001","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajh, hpy001.pdf\'\n'"
"gerona', 'glv041","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glv041.pdf\'\n'"
"2019', '3765643","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2019, 3765643.pdf\'\n'"
"2019', '1287506","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2019, 1287506.pdf\'\n'"
s0008-6363(01)00277-2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(01)00277-2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(01)00277-2.pdf'\n"""
0034-5687(92)90090-j,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0034-5687(92)90090-j.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0034-5687(92)90090-j.pdf'\n"""
"ehjci', 'jev090","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jev090.pdf\'\n'"
"ajcn', '87.3.778","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 87.3.778.pdf\'\n'"
"2016', '4073618","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 4073618.pdf\'\n'"
"bja', 'aet587","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aet587.pdf\'\n'"
"ptj', '86.8.1107","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 86.8.1107.pdf\'\n'"
s0828-282x(08)70176-4,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0828-282x(08)70176-4.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0828-282x(08)70176-4.pdf'\n"""
"ptj', 'pzx075","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, pzx075.pdf\'\n'"
"hmg', 'ddab100","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/hmg, ddab100.pdf\'\n'"
0008-6363-95-00199-9,
"gerona', '51a.4.m165","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 51a.4.m165.pdf\'\n'"
"gerona', '61.5.480","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 61.5.480.pdf\'\n'"
"ptj', '79.8.749","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 79.8.749.pdf\'\n'"
"2017', '8248725","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 8248725.pdf\'\n'"
"gerona', '51a.3.b232","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 51a.3.b232.pdf\'\n'"
"2016', '9107210","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 9107210.pdf\'\n'"
"ajcn', '70.3.346","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 70.3.346.pdf\'\n'"
0003-9993(94)90138-4,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0003-9993(94)90138-4.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0003-9993(94)90138-4.pdf'\n"""
"2014', '501754","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 501754.pdf\'\n'"
s0895-7061(99)00259-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0895-7061(99)00259-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0895-7061(99)00259-9.pdf'\n"""
"sm', '2019017","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/sm, 2019017.pdf\'\n'"
"occmed', 'kqs192","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqs192.pdf\'\n'"
s1010-7940(97)00220-0,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1010-7940(97)00220-0.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1010-7940(97)00220-0.pdf'\n"""
"2014', '616935","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 616935.pdf\'\n'"
"2007', '682984","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2007, 682984.pdf\'\n'"
"conphys', 'cox026","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cox026.pdf\'\n'"
"occmed', 'kqv015","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqv015.pdf\'\n'"
"ndt', '15.11.1751","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, 15.11.1751.pdf\'\n'"
"ageing', '31.4.255","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, 31.4.255.pdf\'\n'"
"2015', '192479","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 192479.pdf\'\n'"
"gerona', '51a.5.m223","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 51a.5.m223.pdf\'\n'"
"2016', '8164518","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 8164518.pdf\'\n'"
"bja', 'aex164","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aex164.pdf\'\n'"
"2013', '591574","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 591574.pdf\'\n'"
0741-5214(85)90140-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0741-5214(85)90140-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0741-5214(85)90140-5.pdf'\n"""
"2015', '732090","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 732090.pdf\'\n'"
"ijpbs', 'lpr.2021.11.4.l42-46","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ijpbs, lpr.2021.11.4.l42-46.pdf\'\n'"
"occmed', 'kqz014","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqz014.pdf\'\n'"
"bja', 'aeu051","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aeu051.pdf\'\n'"
"ptj', '70.5.287","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 70.5.287.pdf\'\n'"
s0008-6363(98)00132-1,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(98)00132-1.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(98)00132-1.pdf'\n"""
s0765-1597(03)00147-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0765-1597(03)00147-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0765-1597(03)00147-3.pdf'\n"""
"ajcn', '69.5.913","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 69.5.913.pdf\'\n'"
"occmed', 'kqi168","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqi168.pdf\'\n'"
s0014-4835(95)80060-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0014-4835(95)80060-3.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0014-4835(95)80060-3.pdf'\n"""
"rheumatology', 'kew026","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, kew026.pdf\'\n'"
s1010-7940(99)00367-x,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1010-7940(99)00367-x.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1010-7940(99)00367-x.pdf'\n"""
"eurheartj', 'ehac260","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, ehac260.pdf\'\n'"
"ajcn', '67.3.397","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 67.3.397.pdf\'\n'"
"1806-3756', 'e20200134","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/1806-3756, e20200134.pdf\'\n'"
"2012', '512857","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 512857.pdf\'\n'"
"2015', '879272","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 879272.pdf\'\n'"
"2019', '8608317","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2019, 8608317.pdf\'\n'"
"rheumatology', 'keh548","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, keh548.pdf\'\n'"
"ageing', 'afp067","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, afp067.pdf\'\n'"
"2017', '6862041","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 6862041.pdf\'\n'"
"2017', '4823102","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2017, 4823102.pdf\'\n'"
"2012', '874020","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 874020.pdf\'\n'"
"ptj', '76.10.1058","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 76.10.1058.pdf\'\n'"
"ajcn', '84.2.354","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 84.2.354.pdf\'\n'"
"brain', 'awp065","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/brain, awp065.pdf\'\n'"
s1054-3139(03)00070-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1054-3139(03)00070-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1054-3139(03)00070-5.pdf'\n"""
"gerona', '56.10.m618","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 56.10.m618.pdf\'\n'"
0002-9378(92)91349-f,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0002-9378(92)91349-f.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0002-9378(92)91349-f.pdf'\n"""
"gerona', 'glaa011","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glaa011.pdf\'\n'"
"rheumatology', 'key342","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, key342.pdf\'\n'"
"fampra', 'cmt059","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/fampra, cmt059.pdf\'\n'"
s0895-7061(99)00141-7,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0895-7061(99)00141-7.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0895-7061(99)00141-7.pdf'\n"""
s0828-282x(08)70569-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0828-282x(08)70569-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0828-282x(08)70569-5.pdf'\n"""
"ajcn', '81.5.1045","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 81.5.1045.pdf\'\n'"
"2014', '843095","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 843095.pdf\'\n'"
"ptj', '76.1.34","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 76.1.34.pdf\'\n'"
s0008-6363(97)00149-1,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(97)00149-1.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(97)00149-1.pdf'\n"""
"ajcn', '65.6.1845","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 65.6.1845.pdf\'\n'"
"ndt', 'gfh784","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ndt, gfh784.pdf\'\n'"
"clinem', 'dgz266","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/clinem, dgz266.pdf\'\n'"
"sleep', '6.1.36","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/sleep, 6.1.36.pdf\'\n'"
"ageing', '31.4.247","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, 31.4.247.pdf\'\n'"
0012-9615(2002)072[0599:dbaepi]2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0012-9615(2002)072[0599:dbaepi]2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0012-9615(2002)072[0599:dbaepi]2.0.co;2.pdf'\n"""
"cz', 'zow026","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/cz, zow026.pdf\'\n'"
"ajcn', '72.6.1445","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 72.6.1445.pdf\'\n'"
"jn', 'nxy048","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/jn, nxy048.pdf\'\n'"
"2016', '4583674","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 4583674.pdf\'\n'"
"ejcts', 'ezx013","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejcts, ezx013.pdf\'\n'"
"conphys', 'cot008","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cot008.pdf\'\n'"
s0008-6363(97)00251-4,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0008-6363(97)00251-4.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0008-6363(97)00251-4.pdf'\n"""
0002-9149(85)90650-2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0002-9149(85)90650-2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0002-9149(85)90650-2.pdf'\n"""
"humrep', 'deq172","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/humrep, deq172.pdf\'\n'"
"milmed', '163.11.770","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, 163.11.770.pdf\'\n'"
"icb', 'icx069","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, icx069.pdf\'\n'"
"ptj', '81.12.1889","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 81.12.1889.pdf\'\n'"
"2015', '618291","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 618291.pdf\'\n'"
"milmed', 'usz003","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, usz003.pdf\'\n'"
"2015', '849809","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 849809.pdf\'\n'"
"2020', '2608730","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2020, 2608730.pdf\'\n'"
"gerona', 'glq109","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glq109.pdf\'\n'"
"gerona', '58.8.m734","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 58.8.m734.pdf\'\n'"
"ehjci', 'jew150","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jew150.pdf\'\n'"
"gerona', 'glq137","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glq137.pdf\'\n'"
"2011', '329643","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2011, 329643.pdf\'\n'"
"2022', '9732355","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 9732355.pdf\'\n'"
"jn', '135.5.1124","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/jn, 135.5.1124.pdf\'\n'"
"ajh', 'hps057","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajh, hps057.pdf\'\n'"
"ehjci', 'jeu141","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jeu141.pdf\'\n'"
"2013', '940170","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 940170.pdf\'\n'"
"ajcn', '66.2.334","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 66.2.334.pdf\'\n'"
"ajcn', '77.2.313","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 77.2.313.pdf\'\n'"
icb-icx038,
"brain', 'awn189","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/brain, awn189.pdf\'\n'"
"occmed', '51.5.357","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, 51.5.357.pdf\'\n'"
s0003-9993(03)00436-2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0003-9993(03)00436-2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0003-9993(03)00436-2.pdf'\n"""
"eurheartj', 'eht429","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, eht429.pdf\'\n'"
s1440-2440(04)80009-4,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1440-2440(04)80009-4.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1440-2440(04)80009-4.pdf'\n"""
"chemse', '23.4.417","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/chemse, 23.4.417.pdf\'\n'"
"gerona', 'glu146","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glu146.pdf\'\n'"
"ageing', 'afw191","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, afw191.pdf\'\n'"
"ejcts', 'ezw147","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejcts, ezw147.pdf\'\n'"
"ehjci', 'jez228","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jez228.pdf\'\n'"
"ajcn', '81.4.746","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 81.4.746.pdf\'\n'"
"acem', '63031","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/acem, 63031.pdf\'\n'"
0003-9993(94)90282-8,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0003-9993(94)90282-8.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0003-9993(94)90282-8.pdf'\n"""
"2012', '919051","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 919051.pdf\'\n'"
"ptj', '76.4.387","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 76.4.387.pdf\'\n'"
"2014', '632765","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 632765.pdf\'\n'"
0003-1569(2001)041[0205:eamohw]2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0003-1569(2001)041[0205:eamohw]2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0003-1569(2001)041[0205:eamohw]2.0.co;2.pdf'\n"""
"gerona', 'glu134","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glu134.pdf\'\n'"
"gerona', 'gls237","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, gls237.pdf\'\n'"
"conphys', 'cox050","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, cox050.pdf\'\n'"
0895-7061(96)00238-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0895-7061(96)00238-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0895-7061(96)00238-5.pdf'\n"""
"2014', '192173","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 192173.pdf\'\n'"
s0140-6736(17)32103-7,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0140-6736(17)32103-7.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0140-6736(17)32103-7.pdf'\n"""
"2012', '148729","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2012, 148729.pdf\'\n'"
"annhyg', 'met062","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/annhyg, met062.pdf\'\n'"
s0022-5223(98)70357-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0022-5223(98)70357-5.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0022-5223(98)70357-5.pdf'\n"""
"2022', '8153521","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 8153521.pdf\'\n'"
"2015', '830567","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 830567.pdf\'\n'"
"eurjhf', 'hfq187","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurjhf, hfq187.pdf\'\n'"
"eurheartj', 'ehi737","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, ehi737.pdf\'\n'"
"2015', '378469","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2015, 378469.pdf\'\n'"
"schbul', 'sbv022","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/schbul, sbv022.pdf\'\n'"
"ajcn', '79.3.437","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 79.3.437.pdf\'\n'"
"2014', '675363","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 675363.pdf\'\n'"
"cvr', 'cvab112","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/cvr, cvab112.pdf\'\n'"
"gerona', '51a.1.b30","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 51a.1.b30.pdf\'\n'"
"2022', '9273830","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2022, 9273830.pdf\'\n'"
"gerona', 'gls220","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, gls220.pdf\'\n'"
s0003-4975(10)65214-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0003-4975(10)65214-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0003-4975(10)65214-9.pdf'\n"""
"2021', '6619747","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 6619747.pdf\'\n'"
"cvr', 'cvw095","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/cvr, cvw095.pdf\'\n'"
"2011', '601416","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2011, 601416.pdf\'\n'"
"aje', 'kwp412","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/aje, kwp412.pdf\'\n'"
"occmed', 'kqi087","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/occmed, kqi087.pdf\'\n'"
"ajcn', '66.3.557","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 66.3.557.pdf\'\n'"
"europace', 'eut148","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/europace, eut148.pdf\'\n'"
"ptj', '84.12.1178","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 84.12.1178.pdf\'\n'"
"2014', '728289","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 728289.pdf\'\n'"
s0304-3800(99)00206-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s0304-3800(99)00206-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s0304-3800(99)00206-9.pdf'\n"""
"2014', '370759","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 370759.pdf\'\n'"
"europace', 'eut217","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/europace, eut217.pdf\'\n'"
"icb', '45.3.426","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, 45.3.426.pdf\'\n'"
"schbul', 'sbv033","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/schbul, sbv033.pdf\'\n'"
1080-6032(2000)011[0204:wpadeo]2.3.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/1080-6032(2000)011[0204:wpadeo]2.3.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/1080-6032(2000)011[0204:wpadeo]2.3.co;2.pdf'\n"""
"2016', '5481843","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 5481843.pdf\'\n'"
"2021', '6663575","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2021, 6663575.pdf\'\n'"
"ejcts', 'ezr170","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ejcts, ezr170.pdf\'\n'"
"ageing', '28.6.531","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ageing, 28.6.531.pdf\'\n'"
"2016', '2479597","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2016, 2479597.pdf\'\n'"
"2013', '174541","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2013, 174541.pdf\'\n'"
"ije', 'dyi193","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ije, dyi193.pdf\'\n'"
"ajcn', '66.2.223","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 66.2.223.pdf\'\n'"
"ajcn', '75.5.818","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 75.5.818.pdf\'\n'"
"eurjhf', 'hfp116","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurjhf, hfp116.pdf\'\n'"
"bja', 'aen310","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/bja, aen310.pdf\'\n'"
"ptj', '79.5.476","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ptj, 79.5.476.pdf\'\n'"
"eurheartj', '14.7.969","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, 14.7.969.pdf\'\n'"
"icvts', 'ivw007","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icvts, ivw007.pdf\'\n'"
"ehjci', 'jeab162","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ehjci, jeab162.pdf\'\n'"
s1440-2440(05)80044-1,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1440-2440(05)80044-1.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1440-2440(05)80044-1.pdf'\n"""
"icb', 'ict034","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/icb, ict034.pdf\'\n'"
"conphys', 'coz092","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/conphys, coz092.pdf\'\n'"
s1525-2167(03)00008-8,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1525-2167(03)00008-8.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1525-2167(03)00008-8.pdf'\n"""
"aje', '154.3.251","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/aje, 154.3.251.pdf\'\n'"
0021-9681(78)90096-6,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0021-9681(78)90096-6.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0021-9681(78)90096-6.pdf'\n"""
"2014', '748972","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2014, 748972.pdf\'\n'"
"gerona', '61.7.713","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, 61.7.713.pdf\'\n'"
"0967-3334', '37', '10', '1728","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/0967-3334, 37, 10, 1728.pdf\'\n'"
"gerona', 'glw108","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glw108.pdf\'\n'"
"einstein_journal', '2021ao5940","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/einstein_journal, 2021ao5940.pdf\'\n'"
"eurheartj', 'ehx099","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurheartj, ehx099.pdf\'\n'"
"milmed', 'usy218","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/milmed, usy218.pdf\'\n'"
"rheumatology', 'kes232","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/rheumatology, kes232.pdf\'\n'"
"2020', '1472514","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/2020, 1472514.pdf\'\n'"
"gerona', 'glq182","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/gerona, glq182.pdf\'\n'"
"ajcn', '83.1.24","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/ajcn, 83.1.24.pdf\'\n'"
s1734-1140(10)70242-5,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/springer_non_oa/s1734-1140(10)70242-5.txt data/cpet_articles/full_texts/pdfs/springer_non_oa/s1734-1140(10)70242-5.pdf'\n"""
0009-9236(95)90057-8,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/springer_non_oa/0009-9236(95)90057-8.txt data/cpet_articles/full_texts/pdfs/springer_non_oa/0009-9236(95)90057-8.pdf'\n"""
s1071-3581(03)00659-7,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/springer_non_oa/s1071-3581(03)00659-7.txt data/cpet_articles/full_texts/pdfs/springer_non_oa/s1071-3581(03)00659-7.pdf'\n"""
s1071-3581(03)00626-3,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/springer_non_oa/s1071-3581(03)00626-3.txt data/cpet_articles/full_texts/pdfs/springer_non_oa/s1071-3581(03)00626-3.pdf'\n"""
sms.13223,
expphysiol.2004.029462,
j.1600-0838.2002.00185.x,
jfb.13557,
j.1600-0838.2003.370.x,
sms.12934,
nbm.3889,
00016349.2010.487894,
art.23008,
1365-2435.13505,
cpf.12032,
j.1365-201x.1997.00198.x,
j.1540-8159.2005.00239.x,
j.1540-8175.2007.00380.x,
j.1365-2761.2004.00590.x,
cpf.12226,
expphysiol.2005.031450,
cpf.12187,
j.febslet.2009.11.054,
j.1600-0838.2004.00429.x,
j.1748-1716.2006.01522.x,
j.1600-0838.2005.00463.x,
j.1365-201x.2005.01475.x,
s0048577298970196,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 110, in main\n    interpreter.process_page(page)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 841, in process_page\n    self.render_contents(page.resources, page.contents, ctm=ctm)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 854, in render_contents\n    self.execute(list_value(streams))\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 879, in execute\n    func(*args)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 762, in do_TJ\n    self.device.render_string(self.textstate, seq)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfdevice.py"", line 80, in render_string\n    textstate.linematrix = self.render_string_horizontal(\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfdevice.py"", line 94, in render_string_horizontal\n    for cid in font.decode(obj):\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdffont.py"", line 496, in decode\n    return list(data)\nTypeError: \'PSKeyword\' object is not iterable\n'"
sms.12498,
and.12907,
jcp.21197,
j.1540-8159.1990.tb06900.x,
j.1365-2265.2005.02363.x,
j.1748-1716.1992.tb09421.x,
sms.12463,
j.1600-0838.2010.01111.x,
1471-0528.13738,
micc.12541,
annals.1320.008,
cpf.12197,
jfb.13593,
ajmg.a.40369,
s11745-014-3929-0,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 106, in main\n    for page in PDFPage.get_pages(fp, pagenos,\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfpage.py"", line 122, in get_pages\n    doc = PDFDocument(parser, password=password, caching=caching)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfdocument.py"", line 583, in __init__\n    raise PDFSyntaxError(\'No /Root object! - Is this really a PDF?\')\npdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?\n'"
apha.13212,
j.1600-0838.2006.00580.x,
mus.25120,
j.1399-0004.2002.620414.x,
jez.a.181,
j.1532-950x.1995.tb01291.x,
j.1540-8159.2009.02169.x,
crj.13061,
cpf.12194,
dom.13953,
042516400777591057,
sms.12475,
j.jalz.2016.05.004,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 106, in main\n    for page in PDFPage.get_pages(fp, pagenos,\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfpage.py"", line 122, in get_pages\n    doc = PDFDocument(parser, password=password, caching=caching)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfdocument.py"", line 583, in __init__\n    raise PDFSyntaxError(\'No /Root object! - Is this really a PDF?\')\npdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?\n'"
ep085735,
ggi.13625,
sms.13582,
j.1439-0442.1996.tb00497.x,
j.1600-0838.2009.00977.x,
j.1651-2227.2007.00139.x,
j.1440-1681.2003.03936.x,
042516409x382079,
ppul.22578,
jfb.14461,
j.1475-097x.2011.01023.x,
oby.2006.182,
j.1365-201x.2005.01490.x,
sms.12943,
j.ejheart.2005.07.008,
bip.20196,
ejhf.217,
j.pmrj.2018.01.004,
j.1600-0404.2005.00420.x,
sms.13057,
ana.20460,
j.1464-5491.2007.02117.x,
j.1475-097x.2006.00678.x,
j.2042-3306.1999.tb03788.x,
042516402776181132,
sms.13257,
expphysiol.2006.034223,
042516401776249471,
sms.12997,
j.1399-0012.2004.00265.x,
042516402776117755,
j.1600-0838.2004.405.x,
ejp.1277,
pri.1619,
jfb.14311,
j.1365-2796.2007.01807.x,
j.1600-0838.2005.00480.x,
ana.20881,
j.1365-201x.2004.01390.x,
j.1939-165x.2001.tb00434.x,
j.1475-097x.2007.00729.x,
evj.12711,
sms.13326,
j.1440-1843.2006.00825.x,
j.1365-201x.2002.00990.x,
sms.12993,
ana.1050,
j.1537-2995.2006.00932.x,
j.1469-8986.2008.00717.x,
j.1600-9657.2005.00354.x,
j.1365-2281.2002.00400.x,
j.2042-3306.1993.tb02921.x,
j.1530-0277.2007.00376.x,
ppul.20342,
cpf.12525,
j.pmrj.2015.10.006,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 106, in main\n    for page in PDFPage.get_pages(fp, pagenos,\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfpage.py"", line 122, in get_pages\n    doc = PDFDocument(parser, password=password, caching=caching)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfdocument.py"", line 583, in __init__\n    raise PDFSyntaxError(\'No /Root object! - Is this really a PDF?\')\npdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?\n'"
sms.13084,
art.21693,
j.1600-0838.2007.00637.x,
1365-2435.13006,
dme.12857,
sms.12984,
sms.13330,
ajhb.20529,
j.1365-201x.2001.00830.x,
j.1475-097x.2006.00658.x,
apha.13110,
ecc.13090,
s0014-5793(98)01115-6,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/wiley_non_oa/s0014-5793(98)01115-6.txt data/cpet_articles/full_texts/pdfs/wiley_non_oa/s0014-5793(98)01115-6.pdf'\n"""
aor.12936,
j.1600-0838.2008.00831.x,
j.2042-3306.1994.tb04373.x,
ep088109,
cpf.12461,
cpf.12460,
cpf.12474,
ppul.20575,
acr.23818,
j.1600-0838.2004.00391.x,
mus.20368,
j.1439-0442.1995.tb00368.x,
j.1475-097x.2009.00906.x,
j.1365-2885.1991.tb00833.x,
sms.13289,
ppul.20359,
sms.12418,
j.1469-8986.2009.00826.x,
j.1751-0813.1994.tb03401.x,
j.1475-097x.2007.00725.x,
expphysiol.2009.048975,
jpn.12242,
j.1469-8986.2004.00171.x,
sms.13075,
sms.12425,
ppul.1029,
sms.13277,
j.1439-0442.1993.tb00651.x,
j.1469-8749.2008.03214.x,
apha.13245,
jfb.12590,
ar.1092350204,
sms.13298,
sms.13059,
j.1525-1594.2000.06579.x,
sms.12582,
j.1440-1681.2002.03718.x,
sms.13313,
j.1475-097x.2006.00692.x,
j.1600-079x.2005.00256.x,
j.1600-0838.2005.00451.x,
sms.12540,
expphysiol.2010.054346,
j.2042-3306.1999.tb03786.x,
sms.12608,
ajhb.23148,
j.1475-097x.2006.00674.x,
expphysiol.2010.054783,
pri.1830,
j.2042-3306.1991.tb02750.x,
j.1600-0838.2006.00550.x,
sms.12422,
expphysiol.2004.027839,
vetrec.165.1.22,
sms.12224,
dme.13771,
j.1525-1403.2007.00117.x,
j.1600-0838.2000.010003123.x,
ajhb.20509,
j.2042-3306.1997.tb01629.x,
j.1442-200x.2007.02320.x,
j.1399-543x.2005.00120.x,
cpf.12459,
j.2042-3306.1991.tb02749.x,
sms.12999,
j.1748-1716.2011.02386.x,
cob.12276,
dmrr.608,
j.1460-9592.2003.00024.x,
j.1600-0838.2005.00432.x,
j.1365-2656.2007.01237.x,
j.1600-0838.2004.00424.x,
j.1600-0838.2006.00589.x,
ppul.20438,
j.2042-3306.2010.00298.x,
j.1365-201x.1997.00230.x,
j.1365-201x.1998.0321e.x,
j.2042-3306.1993.tb03008.x,
j.1600-0838.2009.01043.x,
j.1600-0838.2008.00778.x,
j.1365-201x.2003.01135.x,
j.1365-201x.1998.00335.x,
anae.15162,
jhn.12361,
sms.13808,
08035250600599719,
08035250600643244,
dme.13070,
j.1475-097x.2006.00657.x,
j.1095-8649.1997.tb01645.x,
sms.12479,
j.2042-3306.2010.00227.x,
cpf.12205,
evj.13064,
j.1475-097x.2005.00633.x,
j.1440-1681.2006.04361.x,
j.ejheart.2005.05.005,
apha.13009,
j.1600-0838.2008.00830.x,
j.1439-0442.1993.tb00652.x,
ep088800,
ppul.24798,
j.1365-201x.1998.0303f.x,
j.1475-097x.2004.00585.x,
ajhb.23448,
042516401776563490,
jez.2322,
cpf.12570,
j.2042-3306.1996.tb01602.x,
sms.12324,
j.1365-201x.2003.01176.x,
pri.1717,
sms.13370,
j.1748-1716.2006.01596.x,
ppul.20277,
sms.13371,
j.1600-0838.2006.00530.x,
j.1540-8175.2009.00922.x,
jpn.12391,
j.1600-0838.2006.00577.x,
j.1600-0838.2007.00740.x,
j.2041-210x.2010.00057.x,
art.22124,
j.1475-097x.2007.00741.x,
jir.12603,
j.1475-097x.2010.00938.x,
sms.12483,
j.1095-8649.2011.03182.x,
sms.12468,
cpf.12572,
ep088797,
sms.13212,
sms.13574,
ajpendo.1999.276.1.e106,
japplphysiol.01220.2005,
japplphysiol.00045.2010,
jappl.1997.83.2.503,
japplphysiol.00662.2003,
japplphysiol.00122.2008,
jappl.2000.89.2.430,
japplphysiol.01240.2001,
ajpregu.1999.277.5.r1428,
jappl.1997.83.6.2073,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 110, in main\n    interpreter.process_page(page)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 841, in process_page\n    self.render_contents(page.resources, page.contents, ctm=ctm)\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 854, in render_contents\n    self.execute(list_value(streams))\n  File ""/Users/antonhesse/opt/anaconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py"", line 869, in execute\n    name = keyword_name(obj).decode(\'ascii\')\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xa0 in position 0: ordinal not in range(128)\n'"
japplphysiol.00222.2002,
jappl.1999.87.3.1186,
jappl.1999.86.2.598,
japplphysiol.00866.2002,
ajpendo.00052.2005,
jappl.2001.91.3.1055,
jappl.1999.86.3.1048,
jappl.2000.89.5.1903,
japplphysiol.00585.2003,
japplphysiol.00187.2005,
japplphysiol.00767.2005,
japplphysiol.01371.2004,
japplphysiol.00023.2004,
Scandinavian Med Sci Sports - 2019 - P voas - Maximal heart rate assessment in recreational football players A study,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'Med\'\n'"
Diabetes Obesity Metabolism - 2017 - Winding - The effect on glycaemic control of low‐volume high‐intensity interval,"b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'Obesity\'\n'"
s1388-9842(03)00156-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/s1388-9842(03)00156-9.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/s1388-9842(03)00156-9.pdf'\n"""
1548-8659(2001)130<0783:crtvfe>2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/1548-8659(2001)130<0783:crtvfe>2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/1548-8659(2001)130<0783:crtvfe>2.0.co;2.pdf'\n"""
"eurjhf', 'hfp181","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/wiley_oa/eurjhf, hfp181.pdf\'\n'"
"eurjhf', 'hfp168","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/wiley_oa/eurjhf, hfp168.pdf\'\n'"
"eurjhf', 'hfq086","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/wiley_oa/eurjhf, hfq086.pdf\'\n'"
phy2.12415,
s1607-551x(09)70547-9,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/wiley_oa/s1607-551x(09)70547-9.txt data/cpet_articles/full_texts/pdfs/wiley_oa/s1607-551x(09)70547-9.pdf'\n"""
0012-9615(2002)072[0599:dbaepi]2.0.co;2,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/unpaywall_oa/0012-9615(2002)072[0599:dbaepi]2.0.co;2.txt data/cpet_articles/full_texts/pdfs/unpaywall_oa/0012-9615(2002)072[0599:dbaepi]2.0.co;2.pdf'\n"""
s1607-551x(10)70026-7,"b""/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `pdf2txt.py -o data/cpet_articles/full_texts/txts/wiley_oa/s1607-551x(10)70026-7.txt data/cpet_articles/full_texts/pdfs/wiley_oa/s1607-551x(10)70026-7.pdf'\n"""
"eurjhf', 'hfq187","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurjhf, hfq187.pdf\'\n'"
"eurjhf', 'hfp114","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/wiley_oa/eurjhf, hfp114.pdf\'\n'"
"eurjhf', 'hfp116","b'Traceback (most recent call last):\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 115, in <module>\n    if __name__ == \'__main__\': sys.exit(main(sys.argv))\n  File ""/Users/antonhesse/opt/anaconda3/bin/pdf2txt.py"", line 104, in main\n    with open(fname, \'rb\') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: \'data/cpet_articles/full_texts/pdfs/unpaywall_oa/eurjhf, hfp116.pdf\'\n'"
